esphome:
  name: espectre

esp32:
  variant: ESP32C6 
  framework:
    type: esp-idf
    version: 5.5.1
    sdkconfig_options: # https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/wifi.html#how-to-configure-parameters
      CONFIG_PM_ENABLE: n                             # Disable all power management (critical for CSI reliability)
      CONFIG_ESP_WIFI_11AX_SUPPORT: y                 # Enable WiFi 6 (802.11ax) for ESP32-C6
      CONFIG_ESP_WIFI_CSI_ENABLED: y                  # Enable CSI extraction from WiFi packets
      CONFIG_ESP_WIFI_TASK_CORE_ID: '0'               # Pin WiFi task to core 0
      CONFIG_ESP_WIFI_STA_DISCONNECTED_PM_ENABLE: n   # No power save when disconnected (keeps radio active)
      CONFIG_ESP_WIFI_AMPDU_TX_ENABLED: n             # TX aggregation disabled (not needed for CSI capture)
      CONFIG_ESP_WIFI_AMPDU_RX_ENABLED: y             # RX aggregation enabled (improves packet reception)
      CONFIG_ESP_WIFI_STATIC_RX_BUFFER_NUM: '16'      # Hardware DMA RX buffers (16 × 1.6KB = 25.6KB fixed memory)
      CONFIG_ESP_WIFI_DYNAMIC_RX_BUFFER_NUM: '64'     # WiFi layer RX buffers (heap allocated, prevents CSI packet loss)
      CONFIG_ESP_WIFI_DYNAMIC_TX_BUFFER_NUM: '64'     # WiFi layer TX buffers (reduced, traffic generator uses little)
      CONFIG_ESP_WIFI_RX_BA_WIN: '32'                 # AMPDU RX window size (must be ≤ min(2×STATIC_RX, DYNAMIC_RX))
      CONFIG_ESP_WIFI_IRAM_OPT: y                     # Place WiFi code in IRAM (faster execution, +15KB IRAM)
      CONFIG_ESP_WIFI_RX_IRAM_OPT: y                  # Place RX code in IRAM (faster CSI callbacks, +16KB IRAM)
      CONFIG_LWIP_IRAM_OPTIMIZATION: y                # Place LWIP code in IRAM (faster networking, +20KB IRAM)
      CONFIG_LWIP_EXTRA_IRAM_OPTIMIZATION: y          # Additional IRAM optimization
      CONFIG_LWIP_NETIF_LOOPBACK: n                   # Disable loopback (not needed)
      CONFIG_LWIP_NETIF_STATUS_CALLBACK: y            # Enable status callbacks      
      CONFIG_LWIP_UDP_RECVMBOX_SIZE: '32'             # Default: 6. Queue size for incoming UDP packets
      CONFIG_LWIP_MAX_UDP_PCBS: '16'                  # Default: 16. Max simultaneous UDP connections


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE  # ESPHome power save disabled (redundant but explicit)

api:  # Home Assistant integration

web_server:
  port: 80  # HTTP endpoint for debugging

ota:
  - platform: esphome

logger:
  level: INFO
  logs:
    sensor: WARN         # Reduce sensor state logging
    binary_sensor: WARN  # Reduce binary sensor state logging

external_components:
  - source:
      type: local
      path: components
    components: [ espectre ]

espectre:
  traffic_generator_rate: 100   # Packets/sec to gateway (generates CSI data, 0=disabled)
  segmentation_threshold: 1.0   # Motion sensitivity (0.5-10.0, lower=more sensitive)
  segmentation_window_size: 50  # Moving variance window in packets (10-200, larger=smoother)
  # selected_subcarriers: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]  # Keep commented to enable auto-calibration
  hampel_enabled: true          # Enable Hampel filter for turbulence outlier removal
  hampel_window: 7              # Window size for median calculation (3-11, larger=more smoothing)
  hampel_threshold: 4.0         # MAD multiplier (1.0-10.0, lower=more aggressive filtering)

binary_sensor:
  - platform: espectre
    motion:
      name: "Motion Detected"
      device_class: motion

sensor:
  - platform: espectre
    movement:
      name: "Movement Score"      # Current motion intensity value
    threshold:
      name: "Detection Threshold" # Active threshold value
