# ESPectre - ESP32-C5 Configuration
# WiFi CSI-based motion detection with Home Assistant integration
#
# Made for ESPHome - https://github.com/francescopace/espectre
#
# ⚠️ EXPERIMENTAL: This platform has NOT been tested yet.
# ESP32-C5 uses the same modern CSI API as ESP32-C6 with WiFi 6 support.
# Please report your results on GitHub Discussions!
#
# Compatible boards:
# - ESP32-C5-DevKitC
# - ESP32-C5-DevKitM
# - Any ESP32-C5 board
#
# Provisioning:
# - Via BLE: Use the ESPHome app or Home Assistant companion app
# - Via WiFi: Connect to "ESPectre Fallback" AP and configure
# Note: USB provisioning (improv_serial) not yet supported on ESP32-C5

esphome:
  name: espectre
  friendly_name: ESPectre
  min_version: 2025.11.0
  # Uncomment the next line if you have multiple ESPectre devices (adds MAC suffix to name)
  # name_add_mac_suffix: true
  project:
    name: francescopace.espectre
    version: "2.2.0"

esp32:
  variant: ESP32C5
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

# Load ESPectre component from GitHub
external_components:
  - source:
      type: git
      url: https://github.com/francescopace/espectre
      ref: main
    components: [ espectre ]
    refresh: always

# ESPectre - WiFi CSI Motion Detection
espectre:
  id: espectre_csi

# Dashboard import for easy adoption
dashboard_import:
  package_import_url: github://francescopace/espectre/examples/espectre-c5.yaml@main
  import_full_config: true

# WiFi with fallback AP for provisioning
wifi:
  ap:
    ssid: "ESPectre Fallback"

captive_portal:

# Improv provisioning via BLE
esp32_improv:
  authorizer: none

# Note: improv_serial is not yet supported on ESP32-C5

# Logging
logger:

# Home Assistant API
api:

# OTA updates
ota:
  - platform: esphome
