# ESPectre - ESP32-C3 Configuration
# WiFi CSI-based motion detection with Home Assistant integration
#
# Made for ESPHome - https://github.com/francescopace/espectre
#
# ⚠️ EXPERIMENTAL: This platform has NOT been tested yet.
# Please report your results on GitHub Discussions!
#
# Compatible boards:
# - ESP32-C3-DevKitM
# - ESP32-C3-DevKitC
# - LOLIN C3 Mini
# - Seeed XIAO ESP32C3
# - Any ESP32-C3 board
#
# Provisioning:
# - Via BLE: Use the ESPHome app or Home Assistant companion app
# - Via USB: Use ESPHome web tools (https://web.esphome.io)
# - Via WiFi: Connect to "ESPectre Fallback" AP and configure

esphome:
  name: espectre
  friendly_name: ESPectre
  name_add_mac_suffix: true
  project:
    name: francescopace.espectre
    version: "1.0.0"

esp32:
  variant: ESP32C3
  framework:
    type: esp-idf
    version: 5.5.1
    sdkconfig_options:
      # Power Management (critical for CSI reliability)
      CONFIG_PM_ENABLE: n                             # Disable all power management
      CONFIG_ESP_WIFI_STA_DISCONNECTED_PM_ENABLE: n   # No power save when disconnected
      # CSI Feature
      CONFIG_ESP_WIFI_CSI_ENABLED: y                  # Enable CSI extraction from WiFi packets

# Load ESPectre component from GitHub
external_components:
  - source:
      type: git
      url: https://github.com/francescopace/espectre
      ref: main
    components: [ espectre ]
    refresh: always

# ESPectre - WiFi CSI Motion Detection
espectre:
  id: espectre_csi

# Dashboard import for easy adoption
dashboard_import:
  package_import_url: github://francescopace/espectre/examples/espectre-c3.yaml@main
  import_full_config: true

# WiFi with fallback AP for provisioning
wifi:
  ap:
    ssid: "ESPectre Fallback"

captive_portal:

# Improv provisioning via BLE
esp32_improv:
  authorizer: none

# Improv provisioning via USB
improv_serial:

# Logging
logger:

# Home Assistant API
api:

# OTA updates
ota:
  - platform: esphome
