# ESPectre - ESP32-C3 Configuration
# WiFi CSI-based motion detection with Home Assistant integration
#
# Made for ESPHome - https://github.com/francescopace/espectre
#
# Tested boards (community verified):
# - ESP32-C3 Super Mini (AliExpress/Temu, tested by @mvfc)
# - AirM2M Core ESP32-C3 (tested by @WLaoDuo)
#
# ESP32-C3 Super Mini Notes:
# - Set traffic_generator_rate to 94 or less (higher values cause calibration issues)
# - Some cheap clones may require DIO flash mode - see platformio_options below
#
# Provisioning:
# - Via BLE: Use the ESPHome app or Home Assistant companion app
# - Via USB: Use ESPHome web tools (https://web.esphome.io)
# - Via WiFi: Connect to "ESPectre Fallback" AP and configure

esphome:
  name: espectre
  friendly_name: ESPectre
  min_version: 2025.11.0
  # Uncomment the next line if you have multiple ESPectre devices (adds MAC suffix to name)
  # name_add_mac_suffix: true
  # Uncomment for ESP32-C3 Super Mini clones with flash issues (use DIO instead of QIO)
  # platformio_options:
  #   board_build.flash_mode: dio
  project:
    name: francescopace.espectre
    version: "2.2.0"

esp32:
  variant: ESP32C3
  framework:
    type: esp-idf

# Load ESPectre component from GitHub
external_components:
  - source:
      type: git
      url: https://github.com/francescopace/espectre
      ref: main
    components: [ espectre ]
    refresh: always

# ESPectre - WiFi CSI Motion Detection
# Note: For Super Mini boards, keep traffic_generator_rate <= 94
espectre:
  id: espectre_csi
  traffic_generator_rate: 94  # Safe limit for C3 Super Mini boards

# Dashboard import for easy adoption
dashboard_import:
  package_import_url: github://francescopace/espectre/examples/espectre-c3.yaml@main
  import_full_config: true

# WiFi with fallback AP for provisioning
wifi:
  ap:
    ssid: "ESPectre Fallback"

captive_portal:

# Improv provisioning via BLE
esp32_improv:
  authorizer: none

# Improv provisioning via USB
improv_serial:

# Logging
logger:

# Home Assistant API
api:

# OTA updates
ota:
  - platform: esphome
