# ESPectre - ESP32-S3 Development Configuration
# WiFi CSI-based motion detection - LOCAL DEVELOPMENT VERSION
#
# This file uses local components for development.
# For production use, see espectre-s3.yaml (uses GitHub source).
#
# Tested boards:
# - ESP32-S3-DevKitC-1 (WROOM-1-N16R8)
#
# Usage:
# 1. Clone the repository: git clone https://github.com/francescopace/espectre.git
# 2. cd espectre
# 3. Create secrets.yaml with wifi_ssid and wifi_password
# 4. Run: esphome run examples/espectre-s3-dev.yaml

esphome:
  name: espectre
  friendly_name: ESPectre Dev
  min_version: 2025.11.0

esp32:
  variant: ESP32S3
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

# PSRAM support (8MB on most S3 boards)
psram:
  mode: octal
  speed: 80MHz

# Local component for development
external_components:
  - source:
      type: local
      path: ../components
    components: [ espectre ]

# ESPectre - WiFi CSI Motion Detection
# All parameters shown with defaults
espectre:
  id: espectre_csi
  # Motion detection
  traffic_generator_rate: 100   # Packets/sec for CSI generation (0-1000)
  segmentation_threshold: 1.0   # Motion sensitivity (default: 1.0)
  segmentation_window_size: 50  # Analysis window size in packets (10-200)
  # Low-pass filter (noise reduction)
  lowpass_enabled: false        # Enable low-pass filter (default: false)
  lowpass_cutoff: 11.0          # Cutoff frequency in Hz (5.0-20.0)
  # Hampel filter (anti-spikes in turbulence)
  hampel_enabled: false         # Enable outlier removal filter (default: false)
  hampel_window: 7              # Filter window size (3-11, odd numbers)
  hampel_threshold: 4.0         # Outlier detection threshold (1.0-10.0)
  # Subcarrier selection (optional - leave commented for auto-calibration at boot)
  # selected_subcarriers: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

# WiFi (using secrets for development)
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      #bssid: !secret wifi_bssid  # Lock to specific Access Point (useful for mesh networks)

# Logging (DEBUG level for development)
logger:
  level: DEBUG
  logs:
    sensor: INFO
    binary_sensor: INFO

# Home Assistant API
api:

# OTA updates
ota:
  - platform: esphome

# Debug sensors for development
debug:
  update_interval: 5s

sensor:
  - platform: debug
    free:
      name: "Free Heap"
    block:
      name: "Max Free Block"
    loop_time:
      name: "Loop Time"

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"
