# ESPectre - ESP32-S3 Configuration
# WiFi CSI-based motion detection with Home Assistant integration
#
# Made for ESPHome - https://github.com/francescopace/espectre
#
# Provisioning:
# - Via BLE: Use the ESPHome app or Home Assistant companion app
# - Via USB: Use ESPHome web tools (https://web.esphome.io)
# - Via WiFi: Connect to "ESPectre Fallback" AP and configure

esphome:
  name: espectre
  friendly_name: ESPectre
  name_add_mac_suffix: true
  project:
    name: francescopace.espectre
    version: "1.0.0"

esp32:
  variant: ESP32S3
  framework:
    type: esp-idf
    version: 5.5.1
    sdkconfig_options:
      # Power Management (critical for CSI reliability)
      CONFIG_PM_ENABLE: n                             # Disable all power management
      CONFIG_ESP_WIFI_STA_DISCONNECTED_PM_ENABLE: n   # No power save when disconnected
      # CSI Feature
      CONFIG_ESP_WIFI_CSI_ENABLED: y                  # Enable CSI extraction from WiFi packets
      # PSRAM Support (8MB on most S3 boards)
      CONFIG_SPIRAM: y                                # Enable SPIRAM/PSRAM
      CONFIG_SPIRAM_IGNORE_NOTFOUND: y                # Continue if PSRAM not found
      CONFIG_SPIRAM_TYPE_AUTO: y                      # Automatic detection of PSRAM type
      CONFIG_SPIRAM_SPEED_80M: y                      # 80MHz PSRAM clock
      CONFIG_SPIRAM_BOOT_INIT: y                      # Initialize at boot
      CONFIG_SPIRAM_USE_MALLOC: y                     # Use PSRAM for malloc/heap
      CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL: "8192"     # Small allocations (<8KB) use internal RAM
      CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL: "32768"  # Reserve 32KB internal for DMA
      CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY: y    # Required for some operations
      CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: n         # Disable WiFi allocation from PSRAM

# Load ESPectre component from GitHub
external_components:
  - source:
      type: git
      url: https://github.com/francescopace/espectre
      ref: main
    components: [ espectre ]
    refresh: always

# ESPectre - WiFi CSI Motion Detection
espectre:
  id: espectre_csi

# Dashboard import for easy adoption
dashboard_import:
  package_import_url: github://francescopace/espectre/examples/espectre-s3.yaml@main
  import_full_config: true

# WiFi with fallback AP for provisioning
wifi:
  ap:
    ssid: "ESPectre Fallback"

captive_portal:

# Improv provisioning via BLE
esp32_improv:
  authorizer: none

# Improv provisioning via USB
improv_serial:

# Logging
logger:

# Home Assistant API
api:

# OTA updates
ota:
  - platform: esphome
