# ESPectre - ESP32-S2 Configuration
# WiFi CSI-based motion detection with Home Assistant integration
#
# Made for ESPHome - https://github.com/francescopace/espectre
#
# ⚠️ EXPERIMENTAL: This platform has NOT been tested yet.
# Please report your results on GitHub Discussions!
#
# ⚠️ NOTE: ESP32-S2 does NOT have Bluetooth, so only USB and WiFi provisioning are available.
#
# Compatible boards:
# - ESP32-S2-DevKitM
# - ESP32-S2-Saola
# - LOLIN S2 Mini
# - Any ESP32-S2 board
#
# Provisioning:
# - Via USB: Use ESPHome web tools (https://web.esphome.io)
# - Via WiFi: Connect to "ESPectre Fallback" AP and configure

esphome:
  name: espectre
  friendly_name: ESPectre
  min_version: 2025.11.0
  # Uncomment the next line if you have multiple ESPectre devices (adds MAC suffix to name)
  # name_add_mac_suffix: true
  project:
    name: francescopace.espectre
    version: "2.2.0"

esp32:
  variant: ESP32S2
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

# Load ESPectre component from GitHub
external_components:
  - source:
      type: git
      url: https://github.com/francescopace/espectre
      ref: main
    components: [ espectre ]
    refresh: always

# ESPectre - WiFi CSI Motion Detection
espectre:
  id: espectre_csi

# Dashboard import for easy adoption
dashboard_import:
  package_import_url: github://francescopace/espectre/examples/espectre-s2.yaml@main
  import_full_config: true

# WiFi with fallback AP for provisioning
wifi:
  ap:
    ssid: "ESPectre Fallback"

captive_portal:

# NOTE: ESP32-S2 does NOT have Bluetooth - no esp32_improv available

# Improv provisioning via USB
improv_serial:

# Logging
logger:

# Home Assistant API
api:

# OTA updates
ota:
  - platform: esphome
